services:
  hayhooks:
    build:
      context: ./hayhooks
      dockerfile: Dockerfile
    container_name: hayhooks
    ports:
      - "1416:1416"
    volumes:
      - ./pipelines:/pipelines
    environment:
      - OPENAI_API_KEY=${OPENAI_API_KEY}
      - HAYHOOKS_PIPELINES_DIR=/pipelines
  hackstars-client:
    build:
      context: ./client
      dockerfile: Dockerfile
    ports:
      - "8080:80"
    container_name: hackstars-client
    depends_on:
      - hayhooks
