services:
    hayhooks:
        image: 'deepset/hayhooks:main'
        environment:
            - OPENAPI_API_KEY=123
        ports:
            - '1416:1416'
    hackstars-client:
        build:
            context: ./client
            dockerfile: Dockerfile
        ports:
            - '8080:80'
        container_name: hackstars-client